77 pdp template
hlxsites/vg-roadchoice-com pull request #112
Opened 2023-09-19 10:00 UTC by nfarmache-nc

PDP template

Fix  #65 #66 #77 #81

Test URLs:
- Original: https://www.roadchoice.com/parts/27FCRC
- Ours: https://77-pdp-template--vg-roadchoice-com--hlxsites.hlx.page/parts?category=batteries&sku=27FCRC

2023-09-19 16:05 UTC, jonatan-lledo-netcentric requested changes

2023-09-20 10:13 UTC, Lakshmishri requested changes

2023-09-20 12:13 UTC, nfarmache-nc commented on blocks/pdp/pdp.js
> +  const colKeys = ['Base Part Number',
thanks for the suggestion, I'm using that json now

2023-09-20 13:14 UTC, Lakshmishri requested changes

2023-09-20 13:14 UTC, Lakshmishri commented on blocks/pdp/pdp.css
> +.pdp-catalogs-list-link a,
Can you use class names for the link, so if change the tag in that case we won't styling issues

2023-09-20 13:26 UTC, jonatan-lledo-netcentric approved these changes

2023-09-20 13:54 UTC, nfarmache-nc commented on blocks/pdp/pdp.css
> +.pdp-catalogs-list-link a,
I actually removed the styles completely since they are already in style.css

2023-09-20 14:55 UTC, Lakshmishri approved these changes

2023-09-20 14:55 UTC, merged