78 product subcategory template
hlxsites/vg-roadchoice-com pull request #128
Opened 2023-09-28 09:00 UTC by jonatan-lledo-netcentric

except for those cases where the `rc-[subcategory].json` file is not previewed, or the 2 edge cases of _bumpers_ and _brake-chambers_
the subcategory page loads dynamically based on the parameter in the URL "category"
Tested using _batteries_ and _antennas_ files

also, it handles a 404 page in case something g goes wrong

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/part-category/?category=antennas
- After: https://78-product-subcategory-template--vg-roadchoice-com--hlxsites.hlx.page/part-category/?category=antennas

2023-09-28 12:23 UTC, manuel-vara requested changes

2023-09-28 12:23 UTC, manuel-vara commented on blocks/results-list/product-card.js
> +  const linkUrl = `${baseUrl}/${category}/${partNumber}`;
To align with PDP page the link should be like this example:  /parts?category=batteries&sku=27FCRC

2023-09-28 12:23 UTC, manuel-vara commented on blocks/results-list/product-card.js
>    const repository = 'https://adobe.sharepoint.com/:i:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/vg-roadchoice-com';
Path to Franklin hosted images should be like this example: https://main--vg-roadchoice-com--hlxsites.hlx.page/media/images/media_132095a2f3e1309f212937f07494cdacb7c1b9fb5.jpeg?width=2000&format=webply&optimize=medium

If image is not found then it should be going to look into existing images repo: `parts.trucklibrary.com` , example: https://parts.trucklibrary.com/image/VolvoGroupNorthAmericaLLC/55768-27CRC.0?$s7product$?width=2000&format=webply&optimize=medium 

You can have a look at how images are handled currently in PDP here: 
https://github.com/hlxsites/vg-roadchoice-com/pull/118

2023-09-28 14:17 UTC, Lakshmishri requested changes

2023-09-28 14:17 UTC, Lakshmishri commented on blocks/results-list/product-card.js
>    const repository = 'https://adobe.sharepoint.com/:i:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/vg-roadchoice-com';
Like said by manuel, fetch from json file where you have to filter by part number, which is found in pdp file under function` fetchPartImages`

2023-09-28 14:17 UTC, Lakshmishri commented on templates/part-category/part-category.js
> +  if (hasCategory) {
why not do this instead 
```
const category = urlParams.get('category');
if(category) {
 return category;
 }
 return null; 
```
 if would take care the checking of empty string

2023-09-28 16:36 UTC, nfarmache-nc approved these changes

2023-09-29 07:58 UTC, Lakshmishri approved these changes

2023-09-29 08:53 UTC, manuel-vara approved these changes

2023-09-29 09:05 UTC, merged