Blog index redirected in all sections to query-index file
hlxsites/vg-roadchoice-com pull request #132
Opened 2023-10-03 09:14 UTC by SantiagoHomps-NC

Fix #123

Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/
- After: https://123-blog-index--vg-roadchoice-com--hlxsites.hlx.page/

- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/blog/
- After: https://123-blog-index--vg-roadchoice-com--hlxsites.hlx.page/blog/

- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/blog/dont-cut-corners-on-your-next-brake-job
- After: https://123-blog-index--vg-roadchoice-com--hlxsites.hlx.page/blog/dont-cut-corners-on-your-next-brake-job

2023-10-03 09:27 UTC, manuel-vara requested changes
I see some errors in the console:
<img width="1671" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/116451851/94a28f93-e5e6-4bc7-8123-a073a16cdf91">

2023-10-03 09:28 UTC, jonatan-lledo-netcentric requested changes
apart from that, it's ok to me

2023-10-03 09:28 UTC, jonatan-lledo-netcentric commented on blocks/blog-results/blog-results.js
> -  convertDateExcel,
`convertDateExcel` function is still needed?

2023-10-03 09:31 UTC, SantiagoHomps-NC commented on blocks/blog-results/blog-results.js
> -  convertDateExcel,
no, I missed deleting it... strange the linter didnt remind me

2023-10-03 10:04 UTC, SantiagoHomps-NC commented on blocks/blog-results/blog-results.js
> -  convertDateExcel,
aha! you are looking to the deleted part

2023-10-03 10:22 UTC, jonatan-lledo-netcentric approved these changes

2023-10-04 10:01 UTC, manuel-vara approved these changes

2023-10-04 10:01 UTC, merged