add target blanck to pdf catalogs
hlxsites/vg-roadchoice-com pull request #136
Opened 2023-10-03 12:25 UTC by SantiagoHomps-NC

Fix #95

Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/resources/catalogs/
- After: https://95-pdf-target--vg-roadchoice-com--hlxsites.hlx.page/resources/catalogs/

2023-10-03 12:31 UTC, manuel-vara requested changes
It's working well but can you address this one, please?

2023-10-03 12:54 UTC, SantiagoHomps-NC commented
> It's working well but can you address this one, please? <img alt="image" width="1427" src="https://user-images.githubusercontent.com/116451851/272259323-ca59c5e2-a50f-4995-9dc3-5a7291af5f90.png"> It seems like anchor is pointing to local link

Done! and added a scroll margin

2023-10-03 13:24 UTC, jonatan-lledo-netcentric approved these changes

2023-10-04 09:59 UTC, manuel-vara approved these changes

2023-10-04 09:59 UTC, manuel-vara approved these changes

2023-10-04 10:01 UTC, merged