Update README.md
hlxsites/vg-roadchoice-com pull request #21
Opened 2023-07-06 12:26 UTC by manuel-vara

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #20 

Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/
- After: https://update-readme-text--vg-roadchoice-com--hlxsites.hlx.page/

2023-07-06 12:56 UTC, SantiagoHomps-NC approved these changes

2023-07-07 06:56 UTC, jonatan-lledo-netcentric requested changes
please, update the preview url

2023-07-11 07:06 UTC, manuel-vara commented on README.md
>  - Preview: https://main--{repo}--{owner}.hlx.page/
Requested changes have been done

2023-07-11 07:07 UTC, manuel-vara commented
> please, update the preview url

requested changes done

2023-07-12 06:41 UTC, jonatan-lledo-netcentric approved these changes

2023-07-12 09:40 UTC, merged