Added btn functionality and cookie preference center
hlxsites/vg-roadchoice-com pull request #210
Opened 2023-10-27 09:45 UTC by SantiagoHomps-NC

Added a fuctionality to create button with props to be added and assigned the preference center togglo to `id=preference`
Fix part 3 of issue 207

Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/
- After: https://FIX-cookie-preference-btn--vg-roadchoice-com--hlxsites.hlx.page/

2023-10-27 10:21 UTC, girishdigrajkar commented
Getting error in console; Nothing happens when Clicked on button :

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/50bb0f6b-84fe-4e97-98b0-10be3c439861">

2023-10-27 13:36 UTC, SantiagoHomps-NC commented
> @SantiagoHomps-NC : Getting error in console; Nothing happens when Clicked on button
> 
> <img alt="image" width="1792" src="https://user-images.githubusercontent.com/125972657/278613880-50bb0f6b-84fe-4e97-98b0-10be3c439861.png">

the thing is that is "deactivated" from the code for it not to work in other than live site... I think it has to be merged in order to test

2023-10-31 07:45 UTC, jonatan-lledo-netcentric requested changes

2023-10-31 07:45 UTC, jonatan-lledo-netcentric commented on scripts/scripts.js
> +//  -button and properties -> /*Button*/ [*id=preference,textContent=Cookie preference center*]
for simplicity to the user, it will be easy to remember if all the special text that will be replaced by any tag element share the same pattern, and always in lowercase too, following the "space" example. 
And, for textContent, just say "content"

2023-11-07 10:47 UTC, jonatan-lledo-netcentric approved these changes

2023-11-07 11:04 UTC, manuel-vara approved these changes

2023-11-07 11:13 UTC, jonatan-lledo-netcentric commented on scripts/delayed.js
> +if (!window.location.host.includes('hlx.page') && !window.location.pathname.includes('srcdoc')) {
included again, so Fixed

2023-11-07 12:59 UTC, merged