Footer done
hlxsites/vg-roadchoice-com pull request #22
Opened 2023-07-07 15:55 UTC by SantiagoHomps-NC

Fix #17

Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/
- After: https://17-footer--vg-roadchoice-com--hlxsites.hlx.page/

2023-07-10 10:46 UTC, manuel-vara commented
For the internal urls, could you create the links with the absolute URL, please? 
i.e. Pointing to https://main--vg-roadchoice-com--hlxsites.hlx.page/about instead of /about

2023-07-10 10:47 UTC, manuel-vara requested changes
Please update internal links to use absolute url:  https://main--vg-roadchoice-com--hlxsites.hlx.page/

2023-07-10 12:53 UTC, SantiagoHomps-NC commented
> Please update internal links to use absolute url: https://main--vg-roadchoice-com--hlxsites.hlx.page/

DONE 🚀

2023-07-12 06:51 UTC, jonatan-lledo-netcentric commented on blocks/footer/footer.js
> +      const icon = document.createElement('i');
this can be updated after my Header's PR because I add an updated version of _createElement()_ from mack

2023-07-12 06:51 UTC, jonatan-lledo-netcentric approved these changes

2023-07-12 08:31 UTC, SantiagoHomps-NC commented on blocks/footer/footer.js
> +      const icon = document.createElement('i');
I can change it afterwards

2023-07-12 08:36 UTC, manuel-vara approved these changes

2023-07-12 08:38 UTC, merged