Blog results component
hlxsites/vg-roadchoice-com pull request #71
Opened 2023-07-31 13:16 UTC by SantiagoHomps-NC

Fix #46

Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/drafts/shomps/blog/
- After: https://46-blog-results--vg-roadchoice-com--hlxsites.hlx.page/drafts/shomps/blog/

2023-08-02 08:22 UTC, jonatan-lledo-netcentric requested changes

2023-08-02 08:22 UTC, jonatan-lledo-netcentric commented on styles/styles.css
> +  --ff-fontawesome: fontawesome, "fontawesome Fallback";
for a single word the `"` are optional, but ok.

2023-08-02 15:10 UTC, SantiagoHomps-NC commented on scripts/scripts.js
> +export function getProperties(block) {
Didn't know this function existed, thanks!

2023-08-02 15:10 UTC, SantiagoHomps-NC commented on blocks/recommendations/recommendations.js
> +  const route = '/drafts/shomps/blog-articles.json';
done

2023-08-03 06:50 UTC, manuel-vara approved these changes

2023-08-03 11:12 UTC, jonatan-lledo-netcentric approved these changes

2023-08-03 12:21 UTC, merged