45 catalogs table block
hlxsites/vg-roadchoice-com pull request #86
Opened 2023-08-28 07:54 UTC by LikhitaMate

Fix #45 

Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/
- After: https://45-catalogs-table-block--vg-roadchoice-com--hlxsites.hlx.page

Note: /drafts/likhita/catalogs-table

2023-08-28 09:14 UTC, markovukiceviccn commented on blocks/catalogs-table/catalogs-table.css
> +.allCatalogs ul {
In the future, for css selectors let's use kebab case instead camel case.
In this case this is just a suggestion and not a request for this PR.

2023-08-28 09:18 UTC, markovukiceviccn commented on blocks/catalogs-table/catalogs-table.css
> +
We could use some css nesting to save some bytes and to structure code better (in blocks above and bellow) as in other blocks in this sheet.

2023-08-28 09:20 UTC, markovukiceviccn commented on blocks/catalogs-table/catalogs-table.css
> +  font-weight: 500;
We shouldn't use this property.
Check the README.md file in our root folder for clarification

2023-08-28 09:22 UTC, markovukiceviccn commented on blocks/catalogs-table/catalogs-table.css
> +    font-weight: 400;
Check for every occurrence of this property and replace it with method suggested in the README file.
Check the comment above

2023-08-28 09:28 UTC, markovukiceviccn commented on blocks/catalogs-table/catalogs-table.js
> +resourceFrench.setAttribute('href', '#frenchResources');
We should be consistent with naming convention and display all href values in UPPERCASE.

2023-08-28 09:50 UTC, markovukiceviccn commented on blocks/catalogs-table/catalogs-table.js
> +  results.append(spanishHeading, contentSpanish);
I am not against duplicated code "per se" but in this case I have a strong feeling these three blocks can be refactored as one function without repeating all three blocks.

2023-08-28 10:02 UTC, markovukiceviccn commented on blocks/catalogs-table/catalogs-table.css
> +    border-right: 0px;
We may leave the zero out, it is obolete.

2023-08-28 10:06 UTC, jonatan-lledo-netcentric commented on blocks/catalogs-table/catalogs-table.css
> +
for consistency across the rest of the selectors, please use kebab case. it will be easier to maintain if we follow a minimum of good practices, and that affects the naming conventions. thanks

2023-08-28 10:08 UTC, jonatan-lledo-netcentric commented on blocks/catalogs-table/catalogs-table.css
> +    border-right: 0px;
is better to use the zero alone, without any unit

2023-08-28 10:10 UTC, jonatan-lledo-netcentric commented on blocks/catalogs-table/catalogs-table.css
> +      font-family: "Nexa Black", var(--fallback-ff);
use this instead:
`font-family: var(--headings-ff-black)`

2023-08-28 10:11 UTC, jonatan-lledo-netcentric commented on blocks/catalogs-table/catalogs-table.css
> +  font-family: "Nexa Black", var(--fallback-ff);
same as above, we already have this variable in styles.css

2023-08-28 10:14 UTC, jonatan-lledo-netcentric commented on blocks/catalogs-table/catalogs-table.css
> +@media (max-width: 768px) {
why this resolution is above the other that is less than this one? we usually put the media queries ordered in descendante mode, so 1st the smallest resolution ans below the biggest

2023-08-28 10:17 UTC, jonatan-lledo-netcentric commented on blocks/catalogs-table/catalogs-table.js
> +  results.append(spanishHeading, contentSpanish);
agree, this can be refactored to recive a property with a config object depending if this is th spainsh version or not (or any other version)

2023-08-28 10:20 UTC, jonatan-lledo-netcentric commented on scripts/scripts.js
> +/* Returns a list of properties listed in the block */
this is not needed, because this do the same as the getAlArticles function. if you want to change the name in your code, us an alias

2023-08-28 10:21 UTC, jonatan-lledo-netcentric commented on blocks/catalogs-table/catalogs-table.js
> +  getAllCatolog,
use ```getAllArticles as getAllCatalog``` instead

2023-08-28 10:22 UTC, jonatan-lledo-netcentric requested changes
please, check all the comments and ping me if you need further info

2023-08-28 10:59 UTC, markovukiceviccn commented on blocks/catalogs-table/catalogs-table.css
> +@media (max-width: 768px) {
Yes, mobile first is the approach we follow

2023-09-04 08:24 UTC, jonatan-lledo-netcentric requested changes

2023-09-04 08:24 UTC, jonatan-lledo-netcentric commented on blocks/catalogs-table/catalogs-table.css
> +    border-right: 0px;
this is still as `0px`, and we are using the `0` without any unit

2023-09-04 08:24 UTC, jonatan-lledo-netcentric commented on blocks/catalogs-table/catalogs-table.js
> +  productHeading.textContent = product;
all the textContent options can be as another property in the createElement function like classes or props

2023-09-07 08:59 UTC, jonatan-lledo-netcentric approved these changes

2023-09-07 10:03 UTC, Lakshmishri requested changes

2023-09-08 07:39 UTC, jonatan-lledo-netcentric requested changes

2023-09-08 07:39 UTC, jonatan-lledo-netcentric commented on styles/sections.css
> +resource-list section metadata
is this a commnent? or a selector?

2023-09-08 09:15 UTC, jonatan-lledo-netcentric approved these changes

2023-09-08 09:23 UTC, merged