44 fr roadchoice
hlxsites/vg-roadchoice-com pull request #87
Opened 2023-09-01 12:05 UTC by Sujata928573

Fix  #44 
/drafts/sujata/document

Test URLs:
- Before: https://main--vg-roadchoice-com--hlxsites.hlx.page/
- After: https://44-fr-roadchoice--vg-roadchoice-com--hlxsites.hlx.page/

2023-09-01 12:29 UTC, markovukiceviccn commented on blocks/cards/cards.css
> +}
Code above needs proper formatting and indentation.
Check your IDE settings for proper code formatting and indentation.

2023-09-01 12:29 UTC, markovukiceviccn commented on blocks/cards/cards.css
> +}
In `.cards li a.primary` selector, the `a` is not necessary. 
Hint: tag names are less performant compared to class names ;)

2023-09-01 12:29 UTC, markovukiceviccn commented on blocks/cards/cards.css
> +  font-size: 16px;
Shouldn't we avoid `font-weight` property?

2023-09-01 12:29 UTC, markovukiceviccn commented on blocks/cards/cards.css
>  }
A perfect scenario for nesting ;)

2023-09-01 12:29 UTC, markovukiceviccn commented on blocks/cards/cards.css
> +  aspect-ratio: 0;
probably an unnecessary over-specificity.

2023-09-01 13:18 UTC, jonatan-lledo-netcentric commented on blocks/cards/cards.css
> +  aspect-ratio: 0;
or better, add by js a class to reduce the selector scope

2023-09-01 13:22 UTC, jonatan-lledo-netcentric requested changes
the whole card has to be a link to become a sort of a button, so it needs to use DOM manipulation to set all the structure to be clickable

2023-09-01 13:22 UTC, jonatan-lledo-netcentric commented on blocks/cards/cards.js
> -
please, add createElement from scripts.js:
`import { createElement} from '../../scipts/scripts.js'`
and refactor all the `document.createElement` with our custom function.
thanks

2023-09-07 08:49 UTC, jonatan-lledo-netcentric approved these changes

2023-09-07 08:49 UTC, jonatan-lledo-netcentric commented on blocks/cards/cards.css
>  }
at least not now for this project but we will consider to start using CSS nesting

2023-09-07 09:17 UTC, merged